language: c
sudo: required
matrix:
  include:
    - compiler: gcc
    - compiler: clang
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcovr
      env:
        - BUILD_TYPE=Coverage
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind libyaml-dev
script:
  - make test
  - make valgrind-quiet
  - |
    if [[ "${BUILD_TYPE}" == "Coverage" ]]; then
      make coverage;
      rm build/coverage.xml
      bash <(curl -s https://codecov.io/bash) -g "*test*";
    fi

